### ISSUE TITLE
SSH Capabilities need some sort of scp addition

### ISSUE THREAD

**Issue by stevewhitson** [pagemodel/page-model-tools#1]
SSH Capabilities need some sort of scp addition

**Comment by matt-stevenson** [comment]
Hey Steve,
The SSH testing does include scp capabilities: `.testSSH().scpFileUpload` and `.testSSH().scpFileDownload` 
SCP operations require their own SSH sessions not shared with an SSH connection for running commands, so you will find the scp operations on the same level as `.testSSH().connect`
Sorry for the lack of ssh documentation.
