### ISSUE TITLE
Hello from HN!

### ISSUE THREAD

**Issue by reZach** [pagemodel/page-model-tools#5]
I'm bobblywobbles on HN, I'm glad we connected. Is there anything in specific you'd like me to look at or just give it a general review?
(I used Java while in school so as to say I have a bit of catching up to do here, but it could be that it's good to have a newcomer review the docs!)

**Comment by matt-stevenson** [comment]
A general review would be great.
I've tried to provide a good amount of documentation and examples to get started.  I'm sure there are topics missing, but I don't know where to focus my efforts.  Everyone using it has had some introduction by myself or another, and not started from the documentation alone.
Other then documentation, I'm interested in feedback on the syntax for defining pagemodel files and using the generated chaining api.

I've tried to build this to be very easy to pick up for people new to Java.  So any feedback on that would be great too.

**Comment by matt-stevenson** [comment]
You can email me at matt@pagemodel.org or in [page-model-tools.slack.com](https://page-model-tools.slack.com)

**Comment by reZach** [comment]
Hi @matt-stevenson, I figured it would be easy to reply here. Thank you for some time while I was able to look at this [from a newcomer's perspective].

1. From my perspective, I would find it helpful if you had documentation that isn't _purely_ for reference. I understand the necessity to add documentation that explains every method call, parameter and return value, but I found it hard to grasp how everything kinda worked together from this repo alone. I had to look at another blog post and that gave me the context at what I feel your repo is solving for. If you don't want to cater to beginners, that's purely your decision, but if you do I would suggest to answer the question "what problem does this repo solve" for visitors to your project? Something like: "Do you want to do integration testing in Java but find it hard or want an easy way to be consistent in your tests? Try out **pagemodel** - a consistent way to define and execute your Java tests" (yes. I know it's more marketing but it helps with understanding and greater adoption).

2. I didn't feel I would provide helpful feedback on the syntax, purely out of lack of experience in this sort of testing in Java. I don't want to suggest something with my limited exposure to the ecosystem to make something less recognizable to someone who has worked with similar tools here. I did find the general format of `element_line = [displayed] element_name [element_tester] find_by [click_nav] [modifiers]` makes sense and is intuitive, which is important in my opinion [to be intuitive].

3. I feel your chaining API works. Personally, I'm not a fan of them myself, (I'm more familiar with XUnit - which has a similar chaining API) - I find that I can never remember what methods work with other methods as the names of these methods have more human-readable names, I would much rather prefer `Assert.IsEqual(myvariable, 4);` but that is just me and I don't represent everyone's opinions. To that point, some of your methods for say within the ComparableTester return a PageModel, but some return a ComparableTester, or StringTester - how do I easily know with just the method name myself which methods I can call without consulting the documentation for each method? Something to consider, I'm not sure if I was building the same type of project how I'd go about it.

**Comment by matt-stevenson** [comment]
Thanks for trying it out and the feedback!
Are there any projects with really good introduction content you'd recommend I look at?

**Comment by reZach** [comment]
@matt-stevenson Have you found an example? 
I have been busy with life and slow to reply to this thread.

**Comment by matt-stevenson** [comment]
@reZach not yet, trying to make time to work on it Friday
