### ISSUE TITLE
Documentation On Mail Usage

### ISSUE THREAD

**Issue by manastacio** [pagemodel/page-model-tools#6]
Hi. Hope all is well!

Looking for documentation on intended mail usage and examples. Is there anything available on this?
Also, what is the intended use for LazyMail?

Thanks!

@SeanzieDev @matt-stevenson

**Comment by matt-stevenson** [comment]
There are two examples of mail usage in https://github.com/pagemodel/page-model-tools/blob/0.8.6/docs/advanced-usage.md
I started some mail documentation a while ago.  I'll get it finished up soon, thanks for the push to get it done.

LazyMail does lazy loading of IMAP Message fields.  As mail is fetched and compared only the fields that are being compared are read from the IMAP Message.  The original implementation would do eager loading of all fields retrieving the body and attachments for every Mail Message which could be thousands of messages if using a shared testing accounts.
You should not need to use LazyMail yourself, it will be used by the system when you use Mail.fetchMail

**Comment by manastacio** [comment]
Thank you so much!

**Comment by matt-stevenson** [comment]
I've added my mail documentation work in progress.  Still filling in some sections and adding example code, but there's some info that may be useful.

https://github.com/pagemodel/page-model-tools/blob/0.8.6/docs/mail-testing.md
